# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.cache/wt [current_project]
set_property parent.project_path C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/RF.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/PC.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/nextPC.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/MUX_5bit_4to1.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/MUX_32bits_2to1.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/IR.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/InsMem.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/ExtendSa.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/Extend.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/DR.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/DataMem.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/CU.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/ALU.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/SelectDisplay.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/manualClock.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/display.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/clk_div.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/multiCycleCPU.v
  C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/sources_1/new/Basy3CPU.v
}
read_xdc C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Sherry/Documents/Curriculums/ECOP/multipleCycleCPUBasy3/multipleCycleCPUBasy3.srcs/constrs_1/new/constraints.xdc]

synth_design -top Basy3CPU -part xc7a35tcpg236-1
write_checkpoint -noxdef Basy3CPU.dcp
catch { report_utilization -file Basy3CPU_utilization_synth.rpt -pb Basy3CPU_utilization_synth.pb }
